# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='应用名')),
                ('Version', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='版本号')),
                ('InstallDir', models.CharField(max_length=256, verbose_name='安装目录')),
                ('Port', models.IntegerField(verbose_name='端口')),
                ('Status', models.IntegerField(choices=[(0, 'ON'), (1, 'OFF')], default=1, verbose_name='状态')),
                ('ProductItem', models.SmallIntegerField(choices=[(0, '电商1.0'), (1, '电商2.0'), (2, '电商3.0'), (3, 'NEC'), (4, '运维支撑'), (5, '大数据')], default=6, verbose_name='产品线')),
            ],
            options={
                'verbose_name_plural': '应用',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('HostName', models.CharField(blank=True, max_length=20, null=True, verbose_name='主机名')),
                ('EIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('IIP', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='内网IP')),
                ('Status', models.SmallIntegerField(choices=[(0, 'ON'), (1, 'OFF')], default=0, verbose_name='状态')),
                ('SystemInfo', models.SmallIntegerField(choices=[(0, 'CentOS6.0'), (1, 'CentOS6.5'), (2, 'CentOS7.0'), (4, 'CentOS7.2'), (5, 'Windows2008'), (6, 'Windows2012')], default=0, verbose_name='系统信息')),
                ('Mem', models.IntegerField(default=8, verbose_name='内存')),
                ('CPU', models.IntegerField(default=4)),
                ('SysDisk', models.IntegerField(default=50, verbose_name='系统盘')),
                ('DataDisk', models.IntegerField(default=500, verbose_name='数据盘')),
                ('ProductItem', models.SmallIntegerField(choices=[(0, '电商1.0'), (1, '电商2.0'), (2, '电商3.0'), (3, 'NEC'), (4, '运维支撑'), (5, '大数据')], default=6, verbose_name='产品线')),
                ('ExpirationDate', models.DateField(default=django.utils.timezone.now, verbose_name='到期时间')),
            ],
            options={
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='IIP',
            field=models.ManyToManyField(to='assets.Servers', verbose_name='主机'),
        ),
    ]
